// <auto-generated />
namespace AppEscuelaEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AppEscuela27042020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppEscuela27042020));
        
        string IMigrationMetadata.Id
        {
            get { return "202004280202039_AppEscuela-27-04-2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
